[package]
name = "rust-app-example"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.58"
async-trait = "0.1.56"
rand = "0.8.5"
serde = { version = "1.0.137", features = ["derive"] }
tokio = { version = "1.19.2", features = ["full"] }
validator = { version = "0.15.0", features = ["derive"] }

[dev-dependencies]
assert_matches = "1.5.0"
mockall = "0.11.1"
pretty_assertions = "1.2.1"
rstest = "0.14.0"
serde_json = "1.0.81"
