version: '3.1'

x-db-envs: &db-envs
  POSTGRES_DB: example
  POSTGRES_DB_TEST: example_test
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

services:
  postgres:
    container_name: postgres
    image: postgres:14
    restart: always
    environment: *db-envs
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    container_name: app
    build:
      context: .
    command: cargo run
    volumes:
      - .:/app
    environment:
      << : *db-envs
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/example_test
    depends_on:
      - postgres

volumes:
  pgdata:
    driver: local
