[config]
skip_core_tasks = true

[env.test]
RUST_LOG = "trace"

[tasks.test-watch]
watch = { watch = ["src"] }
run_task = "test"

[tasks.test]
command = "cargo"
args = ["test", "--", "--nocapture", "-q"]

[tasks.ci]
run_task = "test"
dependencies = ["migration-test"]

[tasks.migration]
command = "psqldef"
args = [
    "-U",
    "${POSTGRES_USER}",
    "-W",
    "${POSTGRES_PASSWORD}",
    "-p",
    "${POSTGRES_PORT}",
    "-h",
    "${POSTGRES_HOST}",
    "-f",
    "schema.sql",
    "${POSTGRES_DB}",
]

[tasks.migration-test]
command = "psqldef"
args = [
    "-U",
    "${POSTGRES_USER}",
    "-W",
    "${POSTGRES_PASSWORD}",
    "-p",
    "${POSTGRES_PORT}",
    "-h",
    "${POSTGRES_HOST}",
    "-f",
    "schema.sql",
    "${POSTGRES_DB_TEST}",
]

[tasks.entity]
command = "sea-orm-cli"
args = [
    "generate",
    "entity",
    "-o",
    "src/infrastructure/repository/rdb/entity",
]